WebSEP/Controllers/BonosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloBD;
using System.Collections.Generic;
using System.Linq;

namespace WebSEP.Controllers
{
    public class BonosController : Controller
    {
        private readonly Repositorio db;
        public BonosController(Repositorio db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Bono> listaBonos = db.Bonos
                .Include(bono => bono.Empleado);

            return View(listaBonos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var bono = db.Aumentos
                .Include(bono => bono.Empleado)
                ;

            var listaEmpleados = db.Empleados
                .Select(empleados => new
                {
                    EmpleadoId=empleados.EmpleadoId,
                    Nombres=empleados.Nombres + " "+ empleados.Apellidos,
                }).ToList();

            var selectListaEmpleados = new SelectList(listaEmpleados, "EmpleadoId", "Nombres");

            ViewBag.selectListaEmpleados = selectListaEmpleados;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Bono bono)
        {
            db.Bonos.Add(bono);
            db.SaveChanges();

            TempData["mensaje"] = $"El bono {bono.Nombre} ah sido creado exitosamente";

            return RedirectToAction("Index");
        }
    }
}

WebSEP/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo.Entidades;
using ModeloBD;
using System.Collections;
using System.Collections.Generic;

namespace WebSEP.Controllers
{    
    public class DepartamentoController : Controller
    {
        private readonly Repositorio db;
        public DepartamentoController(Repositorio db)
        {
            this.db = db;
        }
        //Recuperar la lista de materia y envia hacia la vista
        public IActionResult Index()
        {
            //Repositorio db = new Repositorio();
            IEnumerable<Departamento> listaDepartamentos = db.Departamentos;
            return View(listaDepartamentos);
        }

        //Creacion de un nuevo departamento
        //Enviar a un formulrio vacio
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //Grabar una materi 
        [HttpPost]
        public IActionResult Create( Departamento departamento)
        {
            db.Departamentos.Add(departamento);
            db.SaveChanges();

            TempData["mensaje"] = $"El departamento {departamento.Nombre} ah sido creado exitosamente";

            return RedirectToAction("Index");
        }

        //Edicion de un  departamento
        //Enviar a un formulrio con los datos del Departamento
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Departamento departamento = db.Departamentos.Find(id);
            return View(departamento);
        }
        //Actualizar un Departamento
        [HttpPost]
        public IActionResult Edit(Departamento departamento)
        {
            db.Departamentos.Update(departamento);
            db.SaveChanges();

            TempData["mensaje"] = $"El departamento {departamento.Nombre} ah sido actualizado exitosamente";

            return RedirectToAction("Index");
        }

        //Borrado de un  departamento
        //Enviar a un formulrio con los datos del Departamento a Eliminar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Departamento departamento = db.Departamentos.Find(id);
            return View(departamento);
        }
        //Eliminar un Departamento
        [HttpPost]
        public IActionResult Delete(Departamento departamento)
        {
            db.Departamentos.Remove(departamento);
            db.SaveChanges();

            TempData["mensaje"] = $"El departamento ah sido eliminado exitosamente";

            return RedirectToAction("Index");
        }


    }
}

WebSEP/Controllers/SucursalesController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo.Entidades;
using ModeloBD;
using System.Collections.Generic;

namespace WebSEP.Controllers
{
    public class SucursalesController : Controller
    {
        private readonly Repositorio db;
        public SucursalesController(Repositorio db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Sucursal> listaSucursales = db.Sucursals;
            return View(listaSucursales);
        }

        //Creacion de un nuevo Sucursal
        //Enviar a un formulrio vacio
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        //Grabar una materi 
        [HttpPost]
        public IActionResult Create(Sucursal sucursal)
        {
            db.Sucursals.Add(sucursal);
            db.SaveChanges();

            TempData["mensaje"] = $"El sucursal {sucursal.Nombre} ah sido creado exitosamente";

            return RedirectToAction("Index");
        }

        //Edicion de un  sucursal
        //Enviar a un formulrio con los datos del Sucursal
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Sucursal sucursal = db.Sucursals.Find(id);
            return View(sucursal);
        }
        //Actualizar un Sucursal
        [HttpPost]
        public IActionResult Edit(Sucursal sucursal)
        {
            db.Sucursals.Update(sucursal);
            db.SaveChanges();

            TempData["mensaje"] = $"El sucursal {sucursal.Nombre} ah sido actualizado exitosamente";

            return RedirectToAction("Index");
        }

        //Borrado de un  sucursal
        //Enviar a un formulrio con los datos del Sucursal a Eliminar
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Sucursal sucursal = db.Sucursals.Find(id);
            return View(sucursal);
        }
        //Eliminar un Sucursal
        [HttpPost]
        public IActionResult Delete(Sucursal sucursal)
        {
            db.Sucursals.Remove(sucursal);
            db.SaveChanges();

            TempData["mensaje"] = $"El sucursal ah sido eliminado exitosamente";

            return RedirectToAction("Index");
        }



    }
}

WebSEP/Controllers/SueldosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using Modelo.Operaciones;
using ModeloBD;
using System;
using System.Collections.Generic;
using System.Linq;

namespace WebSEP.Controllers
{
    public class SueldosController : Controller
    {
        private readonly Repositorio db;
        int iden;
        public SueldosController(Repositorio db)
        {
            this.db = db;
            
        }
        public IActionResult Index()
        {
            IEnumerable<Empleado> listaEmpleados = db.Empleados
                .Include(empleado => empleado.Sucursal)
                .Include(empleado => empleado.Departamento)
                .Include(empleado => empleado.DesempenoEm)
                .Include(empleado => empleado.DesempenoSc);

            return View(listaEmpleados);




        }
        
        public IActionResult Detalles(int id)
        {
            this.iden = id;
            var sueldo = db.Sueldos
                .Include(sueldo => sueldo.Cargos)
                .Include(sueldo => sueldo.Facturas)
                .Include(sueldo => sueldo.Empleados)
                    .ThenInclude(sueldo => sueldo.Sucursal)
                .Single(sueldo => sueldo.SueldoId == id);
                ;

            var e = db.Empleados
                .Include(em => em.Sueldo)
                .Single(em => em.SueldoId == sueldo.SueldoId)
                ;

            var f = db.Facturas
                .Include(fac => fac.Sueldo)
                .Single(fac => fac.SueldoId == sueldo.SueldoId)
                ;

            var c = db.Cargos
                .Include(carg => carg.Sueldo)
                .Single(carg => carg.SueldoId == sueldo.SueldoId)
                ;

            var s = db.Sueldos
                    .Single(s => s.SueldoId == sueldo.SueldoId)
                    ;
          
            var f1 = sueldo.SueldoBase;

            var facturas = db.Facturas.FirstOrDefault();
            var cargoS = db.Cargos.FirstOrDefault();
            var sBonos = 0f;
            var bono = 0f;

            CalculoSueldos calcSueldos = new CalculoSueldos(c, f);
            var sueldoF = calcSueldos.Sueldo(s);
            
            if (calcSueldos.Aprobado(f))
            {
                //sueldoF = sueldoF + 100;
                sBonos = sueldoF + 100;
                bono =  100;
                TempData["mensaje"] = $"El empleado {e.Nombres +" "+ e.Apellidos}  es acreedor al Bono";

            }
            else
            {
                sBonos = sueldoF;
                TempData["mensaje"] = $"El empleado NO {e.Nombres + " " + e.Apellidos}  es acreedor al Bono";
            }

            decimal decSuelF = Math.Round((decimal)sueldoF, 2);
            decimal decBonos = Math.Round((decimal)sBonos, 2);

            ViewBag.CalcSueldos = decSuelF;
            ViewBag.Bono = bono;
            ViewBag.CalcSueldosB = decBonos;
            return View(sueldo);
        }

        [HttpPost]
        public IActionResult Detalles(Sueldo  sueldo)
        {
            return RedirectToAction("Index");
        }       

        /*
            public IActionResult Detalles(int id)
            {
                var empleado = db.Empleados
                    .Include(empleado => empleado.Sucursal)
                    .Include(empleado => empleado.Departamento)
                    .Include(empleado => empleado.DesempenoEm)
                    .Include(empleado => empleado.DesempenoSc)
                    .Include(empleado => empleado.Sueldo)
                        .ThenInclude(sueldo => sueldo.Facturas)
                    .Include(empleado => empleado.Sueldo)
                        .ThenInclude(sueldo => sueldo.Cargos)
                    .Single(empleado => empleado.EmpleadoId == id)
                    ;


                return View(empleado);
            }
            */
        }
}

WebSEP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SysEval</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><span class="fas fa-chart-pie"></span> SysEval</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">                            
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index"><span class="fas fa-home"></span> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Sucursales" asp-action="Index"><span class="fas fa-building"></span> Sucursales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Departamento" asp-action="Index"><span class="fas fa-layer-group"></span> Departamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Sueldos" asp-action="Index"><span class="fas fa-file-invoice-dollar"></span> Sueldos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Bonos" asp-action="Index"><span class="fas fa-hand-holding-usd"></span> Bonos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SysEval - Javier Yanez - Richard Vaca <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>